owner: FirmansyahDzakwanArifien
repo: upptime

sites:
  - name: Cyphera
    url: https://cyphera.my.id
  - name: Excalidraw
    url: https://excalidraw.cyphera.my.id
  - name: IT-Tools
    url: https://tools.cyphera.my.id
  - name: Status Page
    url: https://status.cyphera.my.id

assignees:
  - FirmansyahDzakwanArifien

status-website:
  cname: status.cyphera.my.id
  name: Cyphera Status
  theme: dark
  introMessage: "Realtime status dan uptime monitoring untuk semua layanan **cyphera.my.id**."
  navbar:
    - title: Homepage
      href: https://cyphera.my.id
